#!/bin/sh

title="$1"

contents_path=./documents/contents

if [ -n "$title" ]; then
    if [ -d "$contents_path"/"$title" ]; then
        echo "Title already exists"
        exit 1
    else
        mkdir "$contents_path"/"$title"
        cp ./documents/templates/script.md "$contents_path"/"$title"/
    fi
else
    echo "Title cannot be empty"
    exit 1
fi
